In [2]:
import pandas as pd
import numpy as np

In [3]:
ds = pd.read_excel(r'C:\Users\HP\Downloads\Dataset (1).xlsx')
ds

       Product   Color Type    Size  Price  Quantity
0       Laptop     Red    A   Small   10.5       5.0
1        Phone    Blue    B  Medium   12.0       7.0
2       Tablet   Green    A   Large   15.0      10.0
3        Mouse     NaN    C   Small    9.5       NaN
4     Keyboard  Yellow  NaN  Medium   14.0       6.0
5      Monitor     Red    B     NaN   11.0       NaN
6      Printer     NaN    A   Large   18.0      12.0
7       Camera    Blue  NaN   Small    NaN       4.0
8      Speaker   Green    C     NaN   16.5       9.0
9       Router     NaN    B  Medium   13.0       NaN
10     Scanner  Yellow    A   Large   20.0      15.0
11       Drive     Red  NaN   Small    NaN       3.0
12     Charger    Blue    C  Medium   14.5       NaN
13       Cable     NaN    A   Large   19.0      11.0
14         Hub   Green    B     NaN   17.0       NaN
15        Dock  Yellow  NaN   Small    8.5       2.0
16     Adapter     Red    C  Medium   12.5       6.0
17        Case    Blue    A     NaN    NaN       5.0
18      Tripod   Green  NaN   Large   21.0      14.0
19       Flash     NaN    B   Small    9.0       NaN
20     Battery  Yellow    C  Medium   13.5       7.0
21  Microphone     Red    A   Large   18.5      12.0
22       Stand    Blue  NaN   Small   10.0       NaN
23       Light   Green    C  Medium   15.5       8.0
24   Projector     NaN    A     NaN    NaN       NaN
25       Drone  Yellow    B   Large   22.0      16.0
26     Console     Red  NaN  Medium   11.5       NaN
27   VRHeadset    Blue    C     NaN   17.0       9.0
28     Gamepad   Green    A   Small    9.8       4.0
29       Modem     NaN    B   Large   19.5      13.0
30         SSD  Yellow  NaN  Medium   14.2       NaN
31         CPU     Red    C   Small   10.2       5.0
32         GPU    Blue    A   Large   20.0      14.0
33         RAM   Green  NaN     NaN    NaN       NaN
34         NAS     NaN    C  Medium   13.8       7.0
35      Switch  Yellow    A   Small    9.0       3.0
36      Server     Red    B   Large   21.5      15.0
37         UPS    Blue  NaN  Medium   12.7       NaN
38      Cooler   Green    C   Small   10.0       4.0
39         Fan  Yellow    B     NaN   18.0       NaN

In [4]:
ds.isnull()

    Product  Color   Type   Size  Price  Quantity
0     False  False  False  False  False     False
1     False  False  False  False  False     False
2     False  False  False  False  False     False
3     False   True  False  False  False      True
4     False  False   True  False  False     False
5     False  False  False   True  False      True
6     False   True  False  False  False     False
7     False  False   True  False   True     False
8     False  False  False   True  False     False
9     False   True  False  False  False      True
10    False  False  False  False  False     False
11    False  False   True  False   True     False
12    False  False  False  False  False      True
13    False   True  False  False  False     False
14    False  False  False   True  False      True
15    False  False   True  False  False     False
16    False  False  False  False  False     False
17    False  False  False   True   True     False
18    False  False   True  False  False     False
19    False   True  False  False  False      True
20    False  False  False  False  False     False
21    False  False  False  False  False     False
22    False  False   True  False  False      True
23    False  False  False  False  False     False
24    False   True  False   True   True      True
25    False  False  False  False  False     False
26    False  False   True  False  False      True
27    False  False  False   True  False     False
28    False  False  False  False  False     False
29    False   True  False  False  False     False
30    False  False   True  False  False      True
31    False  False  False  False  False     False
32    False  False  False  False  False     False
33    False  False   True   True   True      True
34    False   True  False  False  False     False
35    False  False  False  False  False     False
36    False  False  False  False  False     False
37    False  False   True  False  False      True
38    False  False  False  False  False     False
39    False  False  False   True  False      True

In [5]:
ds.describe()

           Price   Quantity
count  35.000000  27.000000
mean   14.505714   8.370370
std     4.090516   4.271085
min     8.500000   2.000000
25%    10.750000   5.000000
50%    14.000000   7.000000
75%    18.000000  12.000000
max    22.000000  16.000000

In [9]:
ds['Product'].mode()

0        Adapter
1        Battery
2            CPU
3          Cable
4         Camera
5           Case
6        Charger
7        Console
8         Cooler
9           Dock
10         Drive
11         Drone
12           Fan
13         Flash
14           GPU
15       Gamepad
16           Hub
17      Keyboard
18        Laptop
19         Light
20    Microphone
21         Modem
22       Monitor
23         Mouse
24           NAS
25         Phone
26       Printer
27     Projector
28           RAM
29        Router
30           SSD
31       Scanner
32        Server
33       Speaker
34         Stand
35        Switch
36        Tablet
37        Tripod
38           UPS
39     VRHeadset
Name: Product, dtype: object

In [10]:
ds['Color'].mode()

0      Blue
1     Green
2       Red
3    Yellow
Name: Color, dtype: object

In [12]:
ds['Color'] =  ds['Color'].fillna(ds['Color'].mode()[0])
ds

       Product   Color Type    Size  Price  Quantity
0       Laptop     Red    A   Small   10.5       5.0
1        Phone    Blue    B  Medium   12.0       7.0
2       Tablet   Green    A   Large   15.0      10.0
3        Mouse    Blue    C   Small    9.5       NaN
4     Keyboard  Yellow  NaN  Medium   14.0       6.0
5      Monitor     Red    B     NaN   11.0       NaN
6      Printer    Blue    A   Large   18.0      12.0
7       Camera    Blue  NaN   Small    NaN       4.0
8      Speaker   Green    C     NaN   16.5       9.0
9       Router    Blue    B  Medium   13.0       NaN
10     Scanner  Yellow    A   Large   20.0      15.0
11       Drive     Red  NaN   Small    NaN       3.0
12     Charger    Blue    C  Medium   14.5       NaN
13       Cable    Blue    A   Large   19.0      11.0
14         Hub   Green    B     NaN   17.0       NaN
15        Dock  Yellow  NaN   Small    8.5       2.0
16     Adapter     Red    C  Medium   12.5       6.0
17        Case    Blue    A     NaN    NaN       5.0
18      Tripod   Green  NaN   Large   21.0      14.0
19       Flash    Blue    B   Small    9.0       NaN
20     Battery  Yellow    C  Medium   13.5       7.0
21  Microphone     Red    A   Large   18.5      12.0
22       Stand    Blue  NaN   Small   10.0       NaN
23       Light   Green    C  Medium   15.5       8.0
24   Projector    Blue    A     NaN    NaN       NaN
25       Drone  Yellow    B   Large   22.0      16.0
26     Console     Red  NaN  Medium   11.5       NaN
27   VRHeadset    Blue    C     NaN   17.0       9.0
28     Gamepad   Green    A   Small    9.8       4.0
29       Modem    Blue    B   Large   19.5      13.0
30         SSD  Yellow  NaN  Medium   14.2       NaN
31         CPU     Red    C   Small   10.2       5.0
32         GPU    Blue    A   Large   20.0      14.0
33         RAM   Green  NaN     NaN    NaN       NaN
34         NAS    Blue    C  Medium   13.8       7.0
35      Switch  Yellow    A   Small    9.0       3.0
36      Server     Red    B   Large   21.5      15.0
37         UPS    Blue  NaN  Medium   12.7       NaN
38      Cooler   Green    C   Small   10.0       4.0
39         Fan  Yellow    B     NaN   18.0       NaN

In [8]:
float(ds['Price'].mean())

14.505714285714285

In [10]:
float(ds['Price'].mean())

14.505714285714285

In [15]:
Q1 = ds['Price'].quantile(0.25)
Q2 = ds['Price'].quantile(0.50)
Q3 = ds['Price'].quantile(0.75)

IQR = Q3 - Q1

print(Q1)
print(Q2)
print(Q3)
print(IQR)

10.75
14.0
18.0
7.25

In [16]:
ds['Price'] = ds['Price'].fillna(ds['Price'].mean())
ds['Price']

0     10.500000
1     12.000000
2     15.000000
3      9.500000
4     14.000000
5     11.000000
6     18.000000
7     14.505714
8     16.500000
9     13.000000
10    20.000000
11    14.505714
12    14.500000
13    19.000000
14    17.000000
15     8.500000
16    12.500000
17    14.505714
18    21.000000
19     9.000000
20    13.500000
21    18.500000
22    10.000000
23    15.500000
24    14.505714
25    22.000000
26    11.500000
27    17.000000
28     9.800000
29    19.500000
30    14.200000
31    10.200000
32    20.000000
33    14.505714
34    13.800000
35     9.000000
36    21.500000
37    12.700000
38    10.000000
39    18.000000
Name: Price, dtype: float64

In [17]:
ds.to_excel(r'C:\Users\HP\Desktop\Kepler Courses\Statistics and Probability for Business\Dataset_cleaned.xlsx', index=False)